=== aravindc/benerator/src/main/resources/org/databene/benerator/benerator-0.4.0.dtd
<!--
<!DOCTYPE setup PUBLIC
    "-//databene/benerator setup DTD 0.4.0//EN"
    "http://databene.org/benerator-0.4.0.dtd">
-->

<!-- The document root, it can list beans, create-entities and run-tasks in arbitrary order. -->
<!ELEMENT setup ((include|property|database|bean|create-entities|run-task|echo)*)>
<!ATTLIST setup default-script CDATA #IMPLIED>
<!ATTLIST setup default-null   CDATA #IMPLIED>

<!-- Includes a properties file. -->
<!ELEMENT include EMPTY>
<!ATTLIST include uri CDATA #IMPLIED>

<!-- Outputs a message to the console. -->
<!ELEMENT echo EMPTY>
<!ATTLIST echo message CDATA #REQUIRED>

<!-- Instantiates a JavaBean of the given class.
     If the 'id' is set, the bean is put into the context with that name.
     If the JavaBean itself has a property named 'id', this one is set to the value specified here. -->
<!ELEMENT bean (property*)>
<!ATTLIST bean
    id    CDATA #REQUIRED
    class CDATA #REQUIRED
>

<!ELEMENT database EMPTY>
<!ATTLIST database
    id       CDATA #REQUIRED
    url      CDATA #IMPLIED
    driver   CDATA #IMPLIED
    user     CDATA #IMPLIED
    password CDATA #IMPLIED
    batch    CDATA #IMPLIED
>

<!-- Declares a JavaBean to be used as consumer, either by referencing an object from the context (ref)
     or by instantiating a JavaBean like with the &lt;bean&gt; tag. -->
<!ELEMENT consumer (property*)>
<!ATTLIST consumer
    id    CDATA #IMPLIED
    class CDATA #IMPLIED
    ref   CDATA #IMPLIED
>

<!-- Sets a JavaBean's property to the simple property specified as 'value' attribute
     or to the object stored in the context with the 'ref'. -->
<!ELEMENT property ((bean|idref)*)>
<!ATTLIST property
    name  CDATA #REQUIRED
    value CDATA #IMPLIED
    ref   CDATA #IMPLIED
>

<!-- Represents a reference to a JavaBean (of the name specified by the 'bean' attribute) from the context. -->
<!ELEMENT idref EMPTY>
<!ATTLIST idref
    bean  CDATA #REQUIRED
>

<!-- Instantiates and executes a JavaBean that implements the Task interface.
     Properties are handled like in the &lt;bean&gt; tag.
     The task is executed 'count' times in a number of 'threads' parallel threads.
     Invocations are executed in groups of size 'pagesize'. -->
<!ELEMENT run-task (property*)>
<!ATTLIST run-task
    class    CDATA #REQUIRED
    count    CDATA #IMPLIED
    pagesize CDATA #IMPLIED
    threads  CDATA #IMPLIED
    pager    CDATA #IMPLIED
>

<!-- Creates entities. If a 'count' is provided the corresponding number of entities is created.
     If no count is provided, entities are created as long as each involved generator is available. -->
<!ELEMENT create-entities ( (id|variable|attribute|consumer)* )>

<!ATTLIST create-entities
    name      CDATA #IMPLIED
    count     CDATA #IMPLIED
    pagesize  CDATA #IMPLIED
    threads   CDATA #IMPLIED
    source    CDATA #IMPLIED
    encoding  CDATA #IMPLIED
    consumer  CDATA #IMPLIED
>

<!-- Defines an ID generator that can be reused in different scopes. -->
<!ELEMENT id EMPTY>
<!ATTLIST id
    name         CDATA #REQUIRED
    strategy     CDATA #REQUIRED
    source       CDATA #IMPLIED
    param        CDATA #IMPLIED
>

<!-- Defines a variable that is recreated by a generator on each entity creation -->
<!ELEMENT variable EMPTY>
<!ATTLIST variable
    name         CDATA #REQUIRED
    type         CDATA #IMPLIED

    generator    CDATA #IMPLIED
    values       CDATA #IMPLIED

    source       CDATA #IMPLIED
    encoding     CDATA #IMPLIED
    selector     CDATA #IMPLIED

    pattern      CDATA #IMPLIED
    generator    CDATA #IMPLIED
    values       CDATA #IMPLIED
    nullQuota    CDATA #IMPLIED
    converter    CDATA #IMPLIED
    region       CDATA #IMPLIED
    locale       CDATA #IMPLIED
    unique (true|false) #IMPLIED

    distribution CDATA #IMPLIED
    variation1   CDATA #IMPLIED
    variation2   CDATA #IMPLIED

    cyclic       (true|false)  #IMPLIED
    proxy        (skip|repeat) #IMPLIED
    proxy-param1 CDATA #IMPLIED
    proxy-param2 CDATA #IMPLIED
>

<!-- Specifies creation of one attribute of an entity. -->
<!ELEMENT attribute EMPTY>
<!-- attribute definition -->
<!ATTLIST attribute
    name         CDATA #REQUIRED
    type         CDATA #IMPLIED
    nullable     CDATA #IMPLIED
    mode (normal|ignored|secret) #IMPLIED
>
<!-- mostly used generator setup -->
<!ATTLIST attribute
    pattern      CDATA  #IMPLIED
    generator    CDATA  #IMPLIED
    values       CDATA  #IMPLIED
    nullQuota    CDATA  #IMPLIED
    converter    CDATA  #IMPLIED
    region       CDATA  #IMPLIED
    locale       CDATA  #IMPLIED
    unique (true|false) #IMPLIED
>
<!-- import setup -->
<!ATTLIST attribute
    source       CDATA #IMPLIED
    encoding     CDATA #IMPLIED
    selector     CDATA #IMPLIED
>
<!-- boolean generator setup -->
<!ATTLIST attribute
    trueQuota    CDATA #IMPLIED
>
<!-- number generator setup -->
<!ATTLIST attribute
    min          CDATA #IMPLIED
    max          CDATA #IMPLIED
    precision    CDATA #IMPLIED
    distribution CDATA #IMPLIED
    variation1   CDATA #IMPLIED
    variation2   CDATA #IMPLIED
>
<!-- String generator setup -->
<!ATTLIST attribute
    script       CDATA #IMPLIED
    minLength    CDATA #IMPLIED
    maxLength    CDATA #IMPLIED
>
<!-- proxy setup -->
<!ATTLIST attribute
    cyclic       (true|false)  #IMPLIED
    proxy        (skip|repeat) #IMPLIED
    proxy-param1 CDATA         #IMPLIED
    proxy-param2 CDATA         #IMPLIED
>

=== aravindc/benerator/src/demo/resources/demo/file/create_by_script.ben.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE setup SYSTEM "http://databene.org/benerator-0.4.0.dtd">
<setup>
    <create-entities name="transaction" count="10">
        <variable name="product" source="demo/file/products.import.csv" distribution="random"/>
        <attribute name="id" type="long" min="1" max="1000000000" distribution="step"/>
        <attribute name="ean_code" source="product.ean_code"/>
        <attribute name="price" source="product.price"/>
        <attribute name="items" type="short" min="1" max="27"/>
        <consumer class="org.databene.platform.script.ScriptedEntityExporter">
            <property name="uri" value="transactions.xml"/>
            <property name="headerScript" value="demo/file/transaction_xml_header.ftl"/>
            <property name="partScript" value="demo/file/transaction_xml_part.ftl"/>
            <property name="footerScript" value="demo/file/transaction_xml_footer.ftl"/>
        </consumer>
    </create-entities>
</setup>
